### ISSUE TITLE
What a coincidence.

### ISSUE THREAD

**Issue by krayc425** [yangsijia-celina/TicTacToe#1]
You learning react too?

**Comment by Vivian-SJ** [comment]
Yeah, my mentor give me a task about front end...

**Comment by yangsijia-celina** [comment]
Yeah, my mentor give me a task about front end...

**Comment by krayc425** [comment]
@Vivian-SJ lol same here, but react is not very difficult I think. Just break things down to components, and that's it. But i don't like JS very much.. No type checking???

**Comment by yangsijia-celina** [comment]
@songkuixi actually, I felt a headache about this long time ago, when I did my J2EE homework...

**Comment by krayc425** [comment]
@Vivian-SJ Got your feelings here. So Microsoft's TypeScript is way much better, however I'm limited to JS.

**Comment by yangsijia-celina** [comment]
@songkuixi Then I am a little luckier than u, because I am asked to use react+Typescript hhh
